# Generated by Django 4.2.29 on 2026-03-15 21:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('product_url', models.URLField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('schedule_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('schedule_day', models.IntegerField(default=0, help_text='Day of week (0=Mon) or day of month')),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('both', 'Both')], default='desktop', max_length=20)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_slack', models.BooleanField(default=False)),
                ('slack_webhook_url', models.URLField(blank=True, default='')),
                ('areas', models.JSONField(default=list, help_text='List of UX areas to analyze')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.team')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('access_status', models.CharField(choices=[('public', 'Public'), ('login_required', 'Login Required'), ('authenticated', 'Authenticated')], default='public', max_length=20)),
                ('proxy_country', models.CharField(blank=True, default='', max_length=2)),
                ('vault_path', models.CharField(blank=True, default='', help_text='Path to stored credentials', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='jobs.job')),
            ],
            options={
                'db_table': 'competitors',
            },
        ),
    ]
