# Generated by Django 4.2.29 on 2026-03-15 21:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='jobs.job')),
            ],
            options={
                'db_table': 'runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunScreenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('device_type', models.CharField(default='desktop', max_length=20)),
                ('page_title', models.CharField(blank=True, default='', max_length=500)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='jobs.competitor')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='runs.run')),
            ],
            options={
                'db_table': 'run_screenshots',
            },
        ),
        migrations.CreateModel(
            name='RunReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0, help_text='Score 0-100')),
                ('summary', models.TextField(blank=True, default='')),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.competitor')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='runs.run')),
            ],
            options={
                'db_table': 'run_reports',
                'unique_together': {('run', 'competitor', 'area')},
            },
        ),
        migrations.CreateModel(
            name='RunOverallScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, help_text='Overall score 0-100')),
                ('rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_scores', to='jobs.competitor')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_scores', to='runs.run')),
            ],
            options={
                'db_table': 'run_overall_scores',
                'unique_together': {('run', 'competitor')},
            },
        ),
    ]
