# Generated by Django 4.2.29 on 2026-03-15 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preflight', 'Preflight'), ('screenshots', 'Screenshots'), ('analyzing', 'Analyzing'), ('scoring', 'Scoring'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('current_phase', models.CharField(blank=True, default='', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('cost_api_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('error_log', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='jobs.job')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunScreenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.URLField()),
                ('page_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=10)),
                ('s3_key', models.CharField(max_length=512)),
                ('thumbnail_s3_key', models.CharField(blank=True, default='', max_length=512)),
                ('viewport_width', models.IntegerField()),
                ('viewport_height', models.IntegerField()),
                ('dom_text', models.TextField(blank=True, default='')),
                ('html_snippet', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='jobs.competitor')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='runs.run')),
            ],
            options={
                'db_table': 'run_screenshots',
            },
        ),
        migrations.CreateModel(
            name='RunReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('summary', models.TextField(default='')),
                ('details', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('previous_score', models.IntegerField(blank=True, null=True)),
                ('score_delta', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.competitor')),
                ('previous_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_report', to='runs.runreport')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='runs.run')),
            ],
            options={
                'db_table': 'run_reports',
            },
        ),
        migrations.CreateModel(
            name='RunOverallScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.IntegerField()),
                ('previous_overall_score', models.IntegerField(blank=True, null=True)),
                ('score_delta', models.IntegerField(blank=True, null=True)),
                ('category_scores', models.JSONField(default=dict)),
                ('top_insights', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_scores', to='jobs.competitor')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_scores', to='runs.run')),
            ],
            options={
                'db_table': 'run_overall_scores',
                'unique_together': {('run', 'competitor')},
            },
        ),
    ]
