# Generated by Django 4.2.29 on 2026-03-16 17:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('preflight', 'Preflight'), ('screenshots', 'Screenshots'), ('analyzing', 'Analyzing'), ('scoring', 'Scoring'), ('comparing', 'Comparing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20),
        ),
        migrations.CreateModel(
            name='RunComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executive_summary', models.TextField(default='')),
                ('feature_matrix', models.JSONField(default=list)),
                ('flow_comparison', models.JSONField(default=list)),
                ('ux_scorecard', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('competitive_position', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to='runs.run')),
            ],
            options={
                'db_table': 'run_comparisons',
            },
        ),
    ]
