# Generated by Django 4.2.29 on 2026-03-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_alter_run_status_runcomparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('preflight', 'Preflight'), ('screenshots', 'Screenshots'), ('discovered', 'Discovered'), ('approved', 'Approved'), ('analyzing', 'Analyzing'), ('scoring', 'Scoring'), ('comparing', 'Comparing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20),
        ),
    ]
