# Generated by Django 4.2.29 on 2026-03-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_alter_run_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='auth_credentials',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
