# Generated by Django 4.2.29 on 2026-03-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_run_auth_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='auth_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='run',
            name='auth_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
