# Generated by Django 4.2.29 on 2026-03-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_run_auth_message_run_auth_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='auth_cookies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
